version: '3'
services:
    react-app:
      container_name: react-app-container
      stdin_open: true
      build:
        context: .
        dockerfile: Dockerfile
        args:
        - APP_NAME=${APP_NAME}
      volumes:
          - "./${APP_NAME}:/usr/src/app"
          - /usr/src/app/node_modules
      expose:
        - 3000
      ports:
        - "${APP_PORT}:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true.

    database-auth:
      image: postgres:14-alpine
      container_name: ${CONTAINER_NAME}
      environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USER}      
        POSTGRES_PASSWORD: ${DATABASE_PASS}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "${DATABASE_PORT}:5432"

    